#!/bin/bash

# author Pablo Yanez Trujillo <shaoran@sakuranohana.org>

# execute this script inside your fortran directory

rm -rf commons.for
ln -fs COMMONS.FOR commons.for

rm -rf comtrn.for
ln -fs COMTRN.FOR comtrn.for
